# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nametag < Formula
  desc "Command-line tool for Nametag"
  homepage "https://getnametag.com"
  version "0.1.20"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nametaginc/cli/releases/download/v0.1.20/nametag_Darwin_x86_64.tar.gz"
      sha256 "94f64bd30c4e0147ac1129d0414f48c9bbb980641767f4064e0a9c7907259c52"

      def install
        bin.install "nametag" => "nametag"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nametaginc/cli/releases/download/v0.1.20/nametag_Darwin_arm64.tar.gz"
      sha256 "5e90a32adea606b407d2d298b0fd7beffcba9c620d379652a850d67c08e0ea56"

      def install
        bin.install "nametag" => "nametag"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nametaginc/cli/releases/download/v0.1.20/nametag_Linux_x86_64.tar.gz"
        sha256 "dd3bf545fc81a16b5e7e045c862a6302d439c7b66fd88a2ed99f9082f692c052"

        def install
          bin.install "nametag" => "nametag"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/nametaginc/cli/releases/download/v0.1.20/nametag_Linux_arm64.tar.gz"
        sha256 "2fb93400b41e78135e3cdef6b29bf8dfcfaeb3d74e72829263664e11d5b3d420"

        def install
          bin.install "nametag" => "nametag"
        end
      end
    end
  end

  def caveats
    <<~EOS
      See https://getnametag.com/docs/cli
    EOS
  end

  test do
    system "#{bin}/nametag", "--version"
  end
end
